// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pb/tbmsg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TbMsgMetaDataProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TbMsgMetaDataProto) Reset() {
	*x = TbMsgMetaDataProto{}
	mi := &file_pb_tbmsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TbMsgMetaDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbMsgMetaDataProto) ProtoMessage() {}

func (x *TbMsgMetaDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tbmsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbMsgMetaDataProto.ProtoReflect.Descriptor instead.
func (*TbMsgMetaDataProto) Descriptor() ([]byte, []int) {
	return file_pb_tbmsg_proto_rawDescGZIP(), []int{0}
}

func (x *TbMsgMetaDataProto) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type TbMsgProcessingStackItemProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuleChainIdMSB int64                  `protobuf:"varint,1,opt,name=ruleChainIdMSB,proto3" json:"ruleChainIdMSB,omitempty"`
	RuleChainIdLSB int64                  `protobuf:"varint,2,opt,name=ruleChainIdLSB,proto3" json:"ruleChainIdLSB,omitempty"`
	RuleNodeIdMSB  int64                  `protobuf:"varint,3,opt,name=ruleNodeIdMSB,proto3" json:"ruleNodeIdMSB,omitempty"`
	RuleNodeIdLSB  int64                  `protobuf:"varint,4,opt,name=ruleNodeIdLSB,proto3" json:"ruleNodeIdLSB,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TbMsgProcessingStackItemProto) Reset() {
	*x = TbMsgProcessingStackItemProto{}
	mi := &file_pb_tbmsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TbMsgProcessingStackItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbMsgProcessingStackItemProto) ProtoMessage() {}

func (x *TbMsgProcessingStackItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tbmsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbMsgProcessingStackItemProto.ProtoReflect.Descriptor instead.
func (*TbMsgProcessingStackItemProto) Descriptor() ([]byte, []int) {
	return file_pb_tbmsg_proto_rawDescGZIP(), []int{1}
}

func (x *TbMsgProcessingStackItemProto) GetRuleChainIdMSB() int64 {
	if x != nil {
		return x.RuleChainIdMSB
	}
	return 0
}

func (x *TbMsgProcessingStackItemProto) GetRuleChainIdLSB() int64 {
	if x != nil {
		return x.RuleChainIdLSB
	}
	return 0
}

func (x *TbMsgProcessingStackItemProto) GetRuleNodeIdMSB() int64 {
	if x != nil {
		return x.RuleNodeIdMSB
	}
	return 0
}

func (x *TbMsgProcessingStackItemProto) GetRuleNodeIdLSB() int64 {
	if x != nil {
		return x.RuleNodeIdLSB
	}
	return 0
}

type TbMsgProcessingCtxProto struct {
	state               protoimpl.MessageState           `protogen:"open.v1"`
	RuleNodeExecCounter int32                            `protobuf:"varint,1,opt,name=ruleNodeExecCounter,proto3" json:"ruleNodeExecCounter,omitempty"`
	Stack               []*TbMsgProcessingStackItemProto `protobuf:"bytes,2,rep,name=stack,proto3" json:"stack,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TbMsgProcessingCtxProto) Reset() {
	*x = TbMsgProcessingCtxProto{}
	mi := &file_pb_tbmsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TbMsgProcessingCtxProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbMsgProcessingCtxProto) ProtoMessage() {}

func (x *TbMsgProcessingCtxProto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tbmsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbMsgProcessingCtxProto.ProtoReflect.Descriptor instead.
func (*TbMsgProcessingCtxProto) Descriptor() ([]byte, []int) {
	return file_pb_tbmsg_proto_rawDescGZIP(), []int{2}
}

func (x *TbMsgProcessingCtxProto) GetRuleNodeExecCounter() int32 {
	if x != nil {
		return x.RuleNodeExecCounter
	}
	return 0
}

func (x *TbMsgProcessingCtxProto) GetStack() []*TbMsgProcessingStackItemProto {
	if x != nil {
		return x.Stack
	}
	return nil
}

type TbMsgProto struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Id               string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	EntityType       string                    `protobuf:"bytes,3,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityIdMSB      int64                     `protobuf:"varint,4,opt,name=entityIdMSB,proto3" json:"entityIdMSB,omitempty"`
	EntityIdLSB      int64                     `protobuf:"varint,5,opt,name=entityIdLSB,proto3" json:"entityIdLSB,omitempty"`
	RuleChainIdMSB   int64                     `protobuf:"varint,6,opt,name=ruleChainIdMSB,proto3" json:"ruleChainIdMSB,omitempty"`
	RuleChainIdLSB   int64                     `protobuf:"varint,7,opt,name=ruleChainIdLSB,proto3" json:"ruleChainIdLSB,omitempty"`
	RuleNodeIdMSB    int64                     `protobuf:"varint,8,opt,name=ruleNodeIdMSB,proto3" json:"ruleNodeIdMSB,omitempty"`
	RuleNodeIdLSB    int64                     `protobuf:"varint,9,opt,name=ruleNodeIdLSB,proto3" json:"ruleNodeIdLSB,omitempty"`
	ClusterPartition int64                     `protobuf:"varint,10,opt,name=clusterPartition,proto3" json:"clusterPartition,omitempty"`
	MetaData         *TbMsgMetaDataProto       `protobuf:"bytes,11,opt,name=metaData,proto3" json:"metaData,omitempty"`
	DataType         int32                     `protobuf:"varint,13,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Data             string                    `protobuf:"bytes,14,opt,name=data,proto3" json:"data,omitempty"`
	Ts               int64                     `protobuf:"varint,15,opt,name=ts,proto3" json:"ts,omitempty"`
	CustomerIdMSB    int64                     `protobuf:"varint,17,opt,name=customerIdMSB,proto3" json:"customerIdMSB,omitempty"`
	CustomerIdLSB    int64                     `protobuf:"varint,18,opt,name=customerIdLSB,proto3" json:"customerIdLSB,omitempty"`
	Ctx              *TbMsgProcessingCtxProto  `protobuf:"bytes,19,opt,name=ctx,proto3" json:"ctx,omitempty"`
	CorrelationIdMSB int64                     `protobuf:"varint,20,opt,name=correlationIdMSB,proto3" json:"correlationIdMSB,omitempty"`
	CorrelationIdLSB int64                     `protobuf:"varint,21,opt,name=correlationIdLSB,proto3" json:"correlationIdLSB,omitempty"`
	Partition        int32                     `protobuf:"varint,22,opt,name=partition,proto3" json:"partition,omitempty"`
	CalculatedFields []*CalculatedFieldIdProto `protobuf:"bytes,23,rep,name=calculatedFields,proto3" json:"calculatedFields,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TbMsgProto) Reset() {
	*x = TbMsgProto{}
	mi := &file_pb_tbmsg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TbMsgProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TbMsgProto) ProtoMessage() {}

func (x *TbMsgProto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tbmsg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TbMsgProto.ProtoReflect.Descriptor instead.
func (*TbMsgProto) Descriptor() ([]byte, []int) {
	return file_pb_tbmsg_proto_rawDescGZIP(), []int{3}
}

func (x *TbMsgProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TbMsgProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TbMsgProto) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *TbMsgProto) GetEntityIdMSB() int64 {
	if x != nil {
		return x.EntityIdMSB
	}
	return 0
}

func (x *TbMsgProto) GetEntityIdLSB() int64 {
	if x != nil {
		return x.EntityIdLSB
	}
	return 0
}

func (x *TbMsgProto) GetRuleChainIdMSB() int64 {
	if x != nil {
		return x.RuleChainIdMSB
	}
	return 0
}

func (x *TbMsgProto) GetRuleChainIdLSB() int64 {
	if x != nil {
		return x.RuleChainIdLSB
	}
	return 0
}

func (x *TbMsgProto) GetRuleNodeIdMSB() int64 {
	if x != nil {
		return x.RuleNodeIdMSB
	}
	return 0
}

func (x *TbMsgProto) GetRuleNodeIdLSB() int64 {
	if x != nil {
		return x.RuleNodeIdLSB
	}
	return 0
}

func (x *TbMsgProto) GetClusterPartition() int64 {
	if x != nil {
		return x.ClusterPartition
	}
	return 0
}

func (x *TbMsgProto) GetMetaData() *TbMsgMetaDataProto {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *TbMsgProto) GetDataType() int32 {
	if x != nil {
		return x.DataType
	}
	return 0
}

func (x *TbMsgProto) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TbMsgProto) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *TbMsgProto) GetCustomerIdMSB() int64 {
	if x != nil {
		return x.CustomerIdMSB
	}
	return 0
}

func (x *TbMsgProto) GetCustomerIdLSB() int64 {
	if x != nil {
		return x.CustomerIdLSB
	}
	return 0
}

func (x *TbMsgProto) GetCtx() *TbMsgProcessingCtxProto {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *TbMsgProto) GetCorrelationIdMSB() int64 {
	if x != nil {
		return x.CorrelationIdMSB
	}
	return 0
}

func (x *TbMsgProto) GetCorrelationIdLSB() int64 {
	if x != nil {
		return x.CorrelationIdLSB
	}
	return 0
}

func (x *TbMsgProto) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *TbMsgProto) GetCalculatedFields() []*CalculatedFieldIdProto {
	if x != nil {
		return x.CalculatedFields
	}
	return nil
}

type CalculatedFieldIdProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CalculatedFieldIdMSB int64                  `protobuf:"varint,1,opt,name=calculatedFieldIdMSB,proto3" json:"calculatedFieldIdMSB,omitempty"`
	CalculatedFieldIdLSB int64                  `protobuf:"varint,2,opt,name=calculatedFieldIdLSB,proto3" json:"calculatedFieldIdLSB,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CalculatedFieldIdProto) Reset() {
	*x = CalculatedFieldIdProto{}
	mi := &file_pb_tbmsg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatedFieldIdProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatedFieldIdProto) ProtoMessage() {}

func (x *CalculatedFieldIdProto) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tbmsg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatedFieldIdProto.ProtoReflect.Descriptor instead.
func (*CalculatedFieldIdProto) Descriptor() ([]byte, []int) {
	return file_pb_tbmsg_proto_rawDescGZIP(), []int{4}
}

func (x *CalculatedFieldIdProto) GetCalculatedFieldIdMSB() int64 {
	if x != nil {
		return x.CalculatedFieldIdMSB
	}
	return 0
}

func (x *CalculatedFieldIdProto) GetCalculatedFieldIdLSB() int64 {
	if x != nil {
		return x.CalculatedFieldIdLSB
	}
	return 0
}

type ToRuleEngineMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantIdMSB    int64                  `protobuf:"varint,1,opt,name=tenantIdMSB,proto3" json:"tenantIdMSB,omitempty"`
	TenantIdLSB    int64                  `protobuf:"varint,2,opt,name=tenantIdLSB,proto3" json:"tenantIdLSB,omitempty"`
	TbMsg          *TbMsgProto            `protobuf:"bytes,6,opt,name=tbMsg,proto3" json:"tbMsg,omitempty"`
	RelationTypes  []string               `protobuf:"bytes,4,rep,name=relationTypes,proto3" json:"relationTypes,omitempty"`
	FailureMessage string                 `protobuf:"bytes,5,opt,name=failureMessage,proto3" json:"failureMessage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToRuleEngineMsg) Reset() {
	*x = ToRuleEngineMsg{}
	mi := &file_pb_tbmsg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToRuleEngineMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToRuleEngineMsg) ProtoMessage() {}

func (x *ToRuleEngineMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tbmsg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToRuleEngineMsg.ProtoReflect.Descriptor instead.
func (*ToRuleEngineMsg) Descriptor() ([]byte, []int) {
	return file_pb_tbmsg_proto_rawDescGZIP(), []int{5}
}

func (x *ToRuleEngineMsg) GetTenantIdMSB() int64 {
	if x != nil {
		return x.TenantIdMSB
	}
	return 0
}

func (x *ToRuleEngineMsg) GetTenantIdLSB() int64 {
	if x != nil {
		return x.TenantIdLSB
	}
	return 0
}

func (x *ToRuleEngineMsg) GetTbMsg() *TbMsgProto {
	if x != nil {
		return x.TbMsg
	}
	return nil
}

func (x *ToRuleEngineMsg) GetRelationTypes() []string {
	if x != nil {
		return x.RelationTypes
	}
	return nil
}

func (x *ToRuleEngineMsg) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

var File_pb_tbmsg_proto protoreflect.FileDescriptor

const file_pb_tbmsg_proto_rawDesc = "" +
	"\n" +
	"\x0epb/tbmsg.proto\x12\bmsgqueue\"\x89\x01\n" +
	"\x12TbMsgMetaDataProto\x12:\n" +
	"\x04data\x18\x01 \x03(\v2&.msgqueue.TbMsgMetaDataProto.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x1dTbMsgProcessingStackItemProto\x12&\n" +
	"\x0eruleChainIdMSB\x18\x01 \x01(\x03R\x0eruleChainIdMSB\x12&\n" +
	"\x0eruleChainIdLSB\x18\x02 \x01(\x03R\x0eruleChainIdLSB\x12$\n" +
	"\rruleNodeIdMSB\x18\x03 \x01(\x03R\rruleNodeIdMSB\x12$\n" +
	"\rruleNodeIdLSB\x18\x04 \x01(\x03R\rruleNodeIdLSB\"\x8a\x01\n" +
	"\x17TbMsgProcessingCtxProto\x120\n" +
	"\x13ruleNodeExecCounter\x18\x01 \x01(\x05R\x13ruleNodeExecCounter\x12=\n" +
	"\x05stack\x18\x02 \x03(\v2'.msgqueue.TbMsgProcessingStackItemProtoR\x05stack\"\x9b\x06\n" +
	"\n" +
	"TbMsgProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"entityType\x18\x03 \x01(\tR\n" +
	"entityType\x12 \n" +
	"\ventityIdMSB\x18\x04 \x01(\x03R\ventityIdMSB\x12 \n" +
	"\ventityIdLSB\x18\x05 \x01(\x03R\ventityIdLSB\x12&\n" +
	"\x0eruleChainIdMSB\x18\x06 \x01(\x03R\x0eruleChainIdMSB\x12&\n" +
	"\x0eruleChainIdLSB\x18\a \x01(\x03R\x0eruleChainIdLSB\x12$\n" +
	"\rruleNodeIdMSB\x18\b \x01(\x03R\rruleNodeIdMSB\x12$\n" +
	"\rruleNodeIdLSB\x18\t \x01(\x03R\rruleNodeIdLSB\x12*\n" +
	"\x10clusterPartition\x18\n" +
	" \x01(\x03R\x10clusterPartition\x128\n" +
	"\bmetaData\x18\v \x01(\v2\x1c.msgqueue.TbMsgMetaDataProtoR\bmetaData\x12\x1a\n" +
	"\bdataType\x18\r \x01(\x05R\bdataType\x12\x12\n" +
	"\x04data\x18\x0e \x01(\tR\x04data\x12\x0e\n" +
	"\x02ts\x18\x0f \x01(\x03R\x02ts\x12$\n" +
	"\rcustomerIdMSB\x18\x11 \x01(\x03R\rcustomerIdMSB\x12$\n" +
	"\rcustomerIdLSB\x18\x12 \x01(\x03R\rcustomerIdLSB\x123\n" +
	"\x03ctx\x18\x13 \x01(\v2!.msgqueue.TbMsgProcessingCtxProtoR\x03ctx\x12*\n" +
	"\x10correlationIdMSB\x18\x14 \x01(\x03R\x10correlationIdMSB\x12*\n" +
	"\x10correlationIdLSB\x18\x15 \x01(\x03R\x10correlationIdLSB\x12\x1c\n" +
	"\tpartition\x18\x16 \x01(\x05R\tpartition\x12L\n" +
	"\x10calculatedFields\x18\x17 \x03(\v2 .msgqueue.CalculatedFieldIdProtoR\x10calculatedFields\"\x80\x01\n" +
	"\x16CalculatedFieldIdProto\x122\n" +
	"\x14calculatedFieldIdMSB\x18\x01 \x01(\x03R\x14calculatedFieldIdMSB\x122\n" +
	"\x14calculatedFieldIdLSB\x18\x02 \x01(\x03R\x14calculatedFieldIdLSB\"\xcf\x01\n" +
	"\x0fToRuleEngineMsg\x12 \n" +
	"\vtenantIdMSB\x18\x01 \x01(\x03R\vtenantIdMSB\x12 \n" +
	"\vtenantIdLSB\x18\x02 \x01(\x03R\vtenantIdLSB\x12*\n" +
	"\x05tbMsg\x18\x06 \x01(\v2\x14.msgqueue.TbMsgProtoR\x05tbMsg\x12$\n" +
	"\rrelationTypes\x18\x04 \x03(\tR\rrelationTypes\x12&\n" +
	"\x0efailureMessage\x18\x05 \x01(\tR\x0efailureMessageB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_tbmsg_proto_rawDescOnce sync.Once
	file_pb_tbmsg_proto_rawDescData []byte
)

func file_pb_tbmsg_proto_rawDescGZIP() []byte {
	file_pb_tbmsg_proto_rawDescOnce.Do(func() {
		file_pb_tbmsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_tbmsg_proto_rawDesc), len(file_pb_tbmsg_proto_rawDesc)))
	})
	return file_pb_tbmsg_proto_rawDescData
}

var file_pb_tbmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_tbmsg_proto_goTypes = []any{
	(*TbMsgMetaDataProto)(nil),            // 0: msgqueue.TbMsgMetaDataProto
	(*TbMsgProcessingStackItemProto)(nil), // 1: msgqueue.TbMsgProcessingStackItemProto
	(*TbMsgProcessingCtxProto)(nil),       // 2: msgqueue.TbMsgProcessingCtxProto
	(*TbMsgProto)(nil),                    // 3: msgqueue.TbMsgProto
	(*CalculatedFieldIdProto)(nil),        // 4: msgqueue.CalculatedFieldIdProto
	(*ToRuleEngineMsg)(nil),               // 5: msgqueue.ToRuleEngineMsg
	nil,                                   // 6: msgqueue.TbMsgMetaDataProto.DataEntry
}
var file_pb_tbmsg_proto_depIdxs = []int32{
	6, // 0: msgqueue.TbMsgMetaDataProto.data:type_name -> msgqueue.TbMsgMetaDataProto.DataEntry
	1, // 1: msgqueue.TbMsgProcessingCtxProto.stack:type_name -> msgqueue.TbMsgProcessingStackItemProto
	0, // 2: msgqueue.TbMsgProto.metaData:type_name -> msgqueue.TbMsgMetaDataProto
	2, // 3: msgqueue.TbMsgProto.ctx:type_name -> msgqueue.TbMsgProcessingCtxProto
	4, // 4: msgqueue.TbMsgProto.calculatedFields:type_name -> msgqueue.CalculatedFieldIdProto
	3, // 5: msgqueue.ToRuleEngineMsg.tbMsg:type_name -> msgqueue.TbMsgProto
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_tbmsg_proto_init() }
func file_pb_tbmsg_proto_init() {
	if File_pb_tbmsg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_tbmsg_proto_rawDesc), len(file_pb_tbmsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_tbmsg_proto_goTypes,
		DependencyIndexes: file_pb_tbmsg_proto_depIdxs,
		MessageInfos:      file_pb_tbmsg_proto_msgTypes,
	}.Build()
	File_pb_tbmsg_proto = out.File
	file_pb_tbmsg_proto_goTypes = nil
	file_pb_tbmsg_proto_depIdxs = nil
}
