package device

import (
	"bytes"
	"encoding/json"
	"io"
	"log"
	"net/http"

	"flow-core/internal/audit"
	"flow-core/internal/httputil"
)

// captureWriter buffers a handler's response so an outer handler can inspect the status
// before deciding what to send to the real client. Used to re-dispatch into the existing
// device-create handler instead of duplicating its logic (quota enforcement, default
// profile resolution, tenant checks, auditing) — duplication would inevitably drift.
type captureWriter struct {
	header http.Header
	body   bytes.Buffer
	status int
}

func newCaptureWriter() *captureWriter {
	return &captureWriter{header: http.Header{}, status: http.StatusOK}
}

func (c *captureWriter) Header() http.Header { return c.header }

func (c *captureWriter) Write(b []byte) (int, error) { return c.body.Write(b) }

func (c *captureWriter) WriteHeader(status int) { c.status = status }

// copyTo replays the captured response onto the real ResponseWriter verbatim.
func (c *captureWriter) copyTo(w http.ResponseWriter) {
	for k, vals := range c.header {
		for _, v := range vals {
			w.Header().Add(k, v)
		}
	}
	w.WriteHeader(c.status)
	_, _ = w.Write(c.body.Bytes())
}

// HandleDeviceWithCredentials processes POST /api/device-with-credentials.
//
// This is what the ThingsBoard UI "Add device" wizard calls when the operator sets a
// credential at creation time (custom access token, MQTT basic, X.509). Without it the
// wizard's credential step fails and the device silently keeps a random auto-generated
// access token.
//
// Body: {"device": {...}, "credentials": {...}} → returns the saved Device (TB contract).
//
// Ordering matters: the credential is VALIDATED BEFORE the device is created, so a
// malformed credential cannot leave a half-created device behind.
func HandleDeviceWithCredentials(w http.ResponseWriter, r *http.Request) {
	claims, ok := httputil.RequireAuth(w, r)
	if !ok {
		return
	}
	tenantId, _ := claims["tenantId"].(string)

	var body struct {
		Device      map[string]interface{} `json:"device"`
		Credentials map[string]interface{} `json:"credentials"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		httputil.WriteError(w, http.StatusBadRequest, "Invalid JSON body")
		return
	}
	if body.Device == nil {
		httputil.WriteError(w, http.StatusBadRequest, "Missing device")
		return
	}

	// Validate the credential up front (no mutation yet).
	var credential deviceCredentialInput
	hasCredential := len(body.Credentials) > 0
	if hasCredential {
		var status int
		var err error
		credential, status, err = normalizeCredentialInput(body.Credentials)
		if err != nil {
			httputil.WriteError(w, status, err.Error())
			return
		}
	}

	// Re-dispatch into the canonical device create/update handler.
	deviceJSON, err := json.Marshal(body.Device)
	if err != nil {
		httputil.WriteError(w, http.StatusBadRequest, "Invalid device payload")
		return
	}
	inner := r.Clone(r.Context())
	inner.Body = io.NopCloser(bytes.NewReader(deviceJSON))
	inner.ContentLength = int64(len(deviceJSON))
	capture := newCaptureWriter()
	HandleDeviceCreateOrUpdate(capture, inner)
	if capture.status != http.StatusOK {
		capture.copyTo(w) // forward the original error verbatim
		return
	}

	if !hasCredential {
		capture.copyTo(w)
		return
	}

	// The saved device carries the id we need to attach the credential to.
	var saved map[string]interface{}
	if err := json.Unmarshal(capture.body.Bytes(), &saved); err != nil {
		capture.copyTo(w)
		return
	}
	deviceID := httputil.ExtractEntityID(saved, "id")
	if deviceID == "" {
		capture.copyTo(w)
		return
	}

	if err := upsertDeviceCredentials(deviceID, credential); err != nil {
		log.Printf("ERROR saving credentials for device %s (device-with-credentials): %v", deviceID, err)
		httputil.WriteError(w, http.StatusInternalServerError, "Device saved but credentials failed")
		return
	}

	deviceName, _ := saved["name"].(string)
	actionData, _ := json.Marshal(map[string]interface{}{
		"credentialsType": credential.Type,
		"autoGenerated":   credential.AutoGenerated,
	})
	userID, _ := claims["userId"].(string)
	userName, _ := claims["sub"].(string)
	audit.Write(audit.Event{
		TenantID:   tenantId,
		UserID:     userID,
		UserName:   userName,
		EntityID:   deviceID,
		EntityType: "DEVICE",
		EntityName: deviceName,
		ActionType: "CREDENTIALS_UPDATED",
		ActionData: string(actionData),
		Status:     "SUCCESS",
	})

	// TB returns the Device from this endpoint; re-read so the response reflects the
	// persisted row rather than the request echo.
	if dev, err := queryDevice(deviceID, tenantId); err == nil {
		httputil.WriteJSON(w, http.StatusOK, dev)
		return
	}
	capture.copyTo(w)
}
