apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zitadel.fullname" . }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
    app.kubernetes.io/component: start
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zitadel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: start
  template:
    metadata:
      labels:
        {{- include "zitadel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: start
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "zitadel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      containers:
        - name: zitadel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - start
            - --config
            - /config/config-yaml
            - --config
            - /secret-config/{{ include "zitadel.secretConfigSecretKey" . }}
            - --masterkeyFromEnv
          env:
            - name: ZITADEL_MASTERKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "zitadel.masterkeySecretName" . }}
                  key: {{ include "zitadel.masterkeySecretKey" . }}
          ports:
            - name: http2-server
              containerPort: 8080
              protocol: TCP
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: /debug/ready
              port: http2-server
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: {{ include "zitadel.probeHost" . | quote }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /debug/ready
              port: http2-server
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: {{ include "zitadel.probeHost" . | quote }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /debug/healthz
              port: http2-server
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: {{ include "zitadel.probeHost" . | quote }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: secret-config
              mountPath: /secret-config
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "zitadel.fullname" . }}-config
        - name: secret-config
          secret:
            secretName: {{ include "zitadel.secretConfigSecretName" . }}
            defaultMode: 0440
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
