{{- if not .Values.masterkey.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zitadel.fullname" . }}-masterkey
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
type: Opaque
stringData:
  masterkey: {{ .Values.masterkey.value | quote }}
---
{{- end }}
{{- if not .Values.secretConfig.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zitadel.fullname" . }}-secret-config
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
type: Opaque
stringData:
  config-yaml: |-
    Database:
      Postgres:
        User:
          Password: {{ .Values.config.database.postgres.user.password | quote }}
        Admin:
          Password: {{ .Values.config.database.postgres.admin.password | quote }}
{{- end }}
