apiVersion: v1
kind: Service
metadata:
  name: {{ include "zitadel.fullname" . }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http2-server
      protocol: TCP
      name: http2-server
      appProtocol: {{ .Values.service.appProtocol }}
  selector:
    {{- include "zitadel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: start
