{{/*
Expand the name of the chart.
*/}}
{{- define "thingsflow.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "thingsflow.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Whether the built-in NATS event plane should require client authentication.
*/}}
{{- define "thingsflow.natsAuthEnabled" -}}
{{- $auth := .Values.nats.auth | default dict -}}
{{- if and (.Values.nats.enabled | default false) ($auth.enabled | default false) -}}
true
{{- else -}}
false
{{- end -}}
{{- end }}

{{/*
Secret that contains the internal NATS username/password.
*/}}
{{- define "thingsflow.natsAuthSecretName" -}}
{{- $auth := .Values.nats.auth | default dict -}}
{{- $existing := $auth.existingSecret | default dict -}}
{{- if $existing.name -}}
{{- $existing.name -}}
{{- else -}}
{{- printf "%s-nats-auth" (include "thingsflow.fullname" .) -}}
{{- end -}}
{{- end }}

{{- define "thingsflow.natsAuthUserKey" -}}
{{- $auth := .Values.nats.auth | default dict -}}
{{- $existing := $auth.existingSecret | default dict -}}
{{- $existing.userKey | default "username" -}}
{{- end }}

{{- define "thingsflow.natsAuthPasswordKey" -}}
{{- $auth := .Values.nats.auth | default dict -}}
{{- $existing := $auth.existingSecret | default dict -}}
{{- $existing.passwordKey | default "password" -}}
{{- end }}

{{/*
Default internal NATS URL for env vars. Kubernetes expands $(NATS_USER) and
$(NATS_PASSWORD) from the env block generated by thingsflow.natsAuthEnv.
*/}}
{{- define "thingsflow.natsURL" -}}
{{- $host := printf "%s-nats:%v" (include "thingsflow.fullname" .) (.Values.nats.clientPort | default 4222) -}}
{{- if eq (include "thingsflow.natsAuthEnabled" .) "true" -}}
{{- printf "nats://$(NATS_USER):$(NATS_PASSWORD)@%s" $host -}}
{{- else -}}
{{- printf "nats://%s" $host -}}
{{- end -}}
{{- end }}

{{/*
Default internal NATS URL for static config files that cannot read Kubernetes
env vars. This requires a concrete password in values; existingSecret users
should set the component's explicit natsUrl if the component cannot expand env.
*/}}
{{- define "thingsflow.natsURLLiteral" -}}
{{- $host := printf "%s-nats:%v" (include "thingsflow.fullname" .) (.Values.nats.clientPort | default 4222) -}}
{{- $auth := .Values.nats.auth | default dict -}}
{{- if and (eq (include "thingsflow.natsAuthEnabled" .) "true") ($auth.password | default "") -}}
{{- printf "nats://%s:%s@%s" ($auth.user | default "thingsflow") $auth.password $host -}}
{{- else -}}
{{- printf "nats://%s" $host -}}
{{- end -}}
{{- end }}

{{/*
NATS URL template for static config files rendered by an init container.
*/}}
{{- define "thingsflow.natsURLTemplate" -}}
{{- $host := printf "%s-nats:%v" (include "thingsflow.fullname" .) (.Values.nats.clientPort | default 4222) -}}
{{- if eq (include "thingsflow.natsAuthEnabled" .) "true" -}}
{{- printf "nats://__NATS_USER__:__NATS_PASSWORD__@%s" $host -}}
{{- else -}}
{{- printf "nats://%s" $host -}}
{{- end -}}
{{- end }}

{{/*
NATS server URL without credentials. Some static clients, such as the RMQTT
NATS bridge, parse authentication from dedicated fields rather than URL userinfo.
*/}}
{{- define "thingsflow.natsURLNoAuthTemplate" -}}
{{- $host := printf "%s-nats:%v" (include "thingsflow.fullname" .) (.Values.nats.clientPort | default 4222) -}}
{{- printf "nats://%s" $host -}}
{{- end }}

{{/*
Env entries used by internal NATS clients when nats.auth.enabled=true.
*/}}
{{- define "thingsflow.natsAuthEnv" -}}
{{- if eq (include "thingsflow.natsAuthEnabled" .) "true" }}
- name: NATS_USER
  valueFrom:
    secretKeyRef:
      name: {{ include "thingsflow.natsAuthSecretName" . }}
      key: {{ include "thingsflow.natsAuthUserKey" . }}
- name: NATS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "thingsflow.natsAuthSecretName" . }}
      key: {{ include "thingsflow.natsAuthPasswordKey" . }}
{{- end -}}
{{- end }}

{{/*
Convert a simple JetStream-style duration string (e.g. "24h", "10m", "1h", "30s")
to an INTEGER number of NANOSECONDS, at Helm render time.

Plan 05-02 / Pitfall 4: the NATS stream guard compares the live `.config.max_age`
(which `nats stream info --json` already reports in nanoseconds) against the intent
value as INTEGER nanoseconds, with NO in-script unit normalization. This helper is
the single render-time conversion point so verify.sh never parses "24h". Supports the
units actually used by the chart's stream values: s, m, h, d. Fails the render loudly
on an unrecognized form rather than silently injecting a wrong integer.
*/}}
{{- define "thingsflow.durationToNanos" -}}
{{- $d := . | toString | trim -}}
{{- if regexMatch "^[0-9]+s$" $d -}}
{{- mul (atoi (trimSuffix "s" $d)) 1000000000 -}}
{{- else if regexMatch "^[0-9]+m$" $d -}}
{{- mul (atoi (trimSuffix "m" $d)) 60000000000 -}}
{{- else if regexMatch "^[0-9]+h$" $d -}}
{{- mul (atoi (trimSuffix "h" $d)) 3600000000000 -}}
{{- else if regexMatch "^[0-9]+d$" $d -}}
{{- mul (atoi (trimSuffix "d" $d)) 86400000000000 -}}
{{- else -}}
{{- fail (printf "thingsflow.durationToNanos: unsupported duration %q (expected <int>{s|m|h|d})" $d) -}}
{{- end -}}
{{- end }}

{{/*
Convert a binary resource quantity (e.g. "1Gi", "8Gi", "512Mi", "50Gi") to an
INTEGER number of BYTES, at Helm render time.

Plan 05-02 / Pitfall 4: the guard compares the live `.config.max_bytes` (bytes) against
the intent as an INTEGER byte count with NO in-script conversion. This helper is the
single render-time conversion point so verify.sh never parses "1Gi". Supports the binary
suffixes used by the chart's stream/PVC values: Ki, Mi, Gi, Ti, plus a bare integer.
Fails the render loudly on an unrecognized form.
*/}}
{{- define "thingsflow.quantityToBytes" -}}
{{- $q := . | toString | trim -}}
{{- if regexMatch "^[0-9]+$" $q -}}
{{- $q -}}
{{- else if regexMatch "^[0-9]+Ki$" $q -}}
{{- mul (atoi (trimSuffix "Ki" $q)) 1024 -}}
{{- else if regexMatch "^[0-9]+Mi$" $q -}}
{{- mul (atoi (trimSuffix "Mi" $q)) 1048576 -}}
{{- else if regexMatch "^[0-9]+Gi$" $q -}}
{{- mul (atoi (trimSuffix "Gi" $q)) 1073741824 -}}
{{- else if regexMatch "^[0-9]+Ti$" $q -}}
{{- mul (atoi (trimSuffix "Ti" $q)) 1099511627776 -}}
{{- else -}}
{{- fail (printf "thingsflow.quantityToBytes: unsupported quantity %q (expected <int>{Ki|Mi|Gi|Ti} or bare bytes)" $q) -}}
{{- end -}}
{{- end }}

{{/*
Secret that contains the Postgres password.
*/}}
{{- define "thingsflow.postgresSecretName" -}}
{{- $existing := .Values.postgres.passwordExistingSecret | default dict -}}
{{- if $existing.name -}}
{{- $existing.name -}}
{{- else -}}
{{- printf "%s-postgres" (include "thingsflow.fullname" .) -}}
{{- end -}}
{{- end }}

{{- define "thingsflow.postgresSecretKey" -}}
{{- $existing := .Values.postgres.passwordExistingSecret | default dict -}}
{{- $existing.key | default "password" -}}
{{- end }}

{{/*
Whether the bundled Dex provider is enabled for local/demo OIDC tests.
*/}}
{{- define "thingsflow.testAuthDexEnabled" -}}
{{- $testAuth := .Values.testAuth | default dict -}}
{{- if and ($testAuth.enabled | default false) (eq ($testAuth.provider | default "dex") "dex") -}}
true
{{- else -}}
false
{{- end -}}
{{- end }}

{{- define "thingsflow.testAuthDexServiceName" -}}
{{- printf "%s-test-auth-dex" (include "thingsflow.fullname" .) -}}
{{- end }}

{{- define "thingsflow.testAuthDexIssuer" -}}
{{- $dex := .Values.testAuth.dex | default dict -}}
{{- $dex.issuer | default (printf "http://localhost:%v/dex" ($dex.port | default 5556)) -}}
{{- end }}

{{- define "thingsflow.testAuthDexInternalBaseURL" -}}
{{- $dex := .Values.testAuth.dex | default dict -}}
{{- printf "http://%s:%v/dex" (include "thingsflow.testAuthDexServiceName" .) ($dex.port | default 5556) -}}
{{- end }}

{{- define "thingsflow.testAuthOidcSecretName" -}}
{{- printf "%s-test-auth-oidc" (include "thingsflow.fullname" .) -}}
{{- end }}
