// Code generated from internal/uicontract/testdata/tb-ui-4.3.1.1.json — the
// UI contract's no-goal entries. Regenerate by re-running the generator in
// nogoals_gen_test.go if the contract changes; the test fails when this table
// drifts from the JSON.
package main

// noGoalEntry is one UI endpoint deliberately declared out of scope. "{id}"
// stands for exactly one path segment (the contract's placeholder UUID).
type noGoalEntry struct {
	method, pattern string
}

var declaredNoGoals = []noGoalEntry{
	{"DELETE", "/api/admin/autoCommitSettings"},
	{"DELETE", "/api/ai/model/{id}"},
	{"DELETE", "/api/apiKey/{id}"},
	{"DELETE", "/api/domain/{id}"},
	{"DELETE", "/api/edge/{id}"},
	{"DELETE", "/api/edge/{id}/asset/{id}"},
	{"DELETE", "/api/edge/{id}/dashboard/{id}"},
	{"DELETE", "/api/edge/{id}/device/{id}"},
	{"DELETE", "/api/edge/{id}/entityView/{id}"},
	{"DELETE", "/api/edge/{id}/ruleChain/{id}"},
	{"DELETE", "/api/mobile/app/{id}"},
	{"DELETE", "/api/mobile/bundle/{id}"},
	{"DELETE", "/api/notification/request/{id}"},
	{"DELETE", "/api/notification/rule/{id}"},
	{"DELETE", "/api/notification/target/{id}"},
	{"DELETE", "/api/notification/template/{id}"},
	{"DELETE", "/api/notification/{id}"},
	{"DELETE", "/api/oauth2/client/{id}"},
	{"DELETE", "/api/queues/{id}"},
	{"DELETE", "/api/ruleChain/{id}/autoAssignToEdge"},
	{"GET", "/api/admin/autoCommitSettings"},
	{"GET", "/api/admin/mail/oauth2/authorize"},
	{"GET", "/api/admin/mail/oauth2/loginProcessingUrl"},
	{"GET", "/api/ai/model"},
	{"GET", "/api/ai/model/{id}"},
	{"GET", "/api/apiKeys"},
	{"GET", "/api/component/{id}"},
	{"GET", "/api/components/{id}"},
	{"GET", "/api/domain/info/{id}"},
	{"GET", "/api/domain/infos"},
	{"GET", "/api/edge/info/{id}"},
	{"GET", "/api/edge/instructions/install/{id}/{id}"},
	{"GET", "/api/edge/instructions/upgrade/{id}/{id}"},
	{"GET", "/api/edge/missingToRelatedRuleChains/{id}"},
	{"GET", "/api/edge/{id}"},
	{"GET", "/api/edge/{id}/assets"},
	{"GET", "/api/edge/{id}/dashboards"},
	{"GET", "/api/edge/{id}/devices"},
	{"GET", "/api/edge/{id}/entityViews"},
	{"GET", "/api/edge/{id}/events"},
	{"GET", "/api/edge/{id}/ruleChains"},
	{"GET", "/api/edge/{id}/upgrade/available"},
	{"GET", "/api/entities/vc/branches"},
	{"GET", "/api/entities/vc/diff/{id}/{id}"},
	{"GET", "/api/entities/vc/entity/{id}/status"},
	{"GET", "/api/entities/vc/info/{id}/{id}/{id}"},
	{"GET", "/api/entities/vc/version"},
	{"GET", "/api/entities/vc/version/{id}"},
	{"GET", "/api/entities/vc/version/{id}/status"},
	{"GET", "/api/lwm2m/deviceProfile/bootstrap/{id}"},
	{"GET", "/api/mobile/app/{id}"},
	{"GET", "/api/mobile/bundle/info/{id}"},
	{"GET", "/api/notification/request/{id}"},
	{"GET", "/api/notification/rule/{id}"},
	{"GET", "/api/notification/target/{id}"},
	{"GET", "/api/notification/template/{id}"},
	{"GET", "/api/oauth2/client/{id}"},
	{"GET", "/api/queueStats"},
	{"GET", "/api/queueStats/{id}"},
	{"GET", "/api/queues/name/{id}"},
	{"GET", "/api/queues/{id}"},
	{"GET", "/api/resource/lwm2m/page"},
	{"GET", "/api/ruleChain/{id}/output/labels"},
	{"GET", "/api/ruleNode/{id}/debugIn"},
	{"POST", "/api/admin/autoCommitSettings"},
	{"POST", "/api/ai/model"},
	{"POST", "/api/ai/model/chat"},
	{"POST", "/api/apiKey"},
	{"POST", "/api/edge/sync/{id}"},
	{"POST", "/api/edge/{id}/asset/{id}"},
	{"POST", "/api/edge/{id}/dashboard/{id}"},
	{"POST", "/api/edge/{id}/device/{id}"},
	{"POST", "/api/edge/{id}/entityView/{id}"},
	{"POST", "/api/edge/{id}/ruleChain/{id}"},
	{"POST", "/api/edge/{id}/{id}/root"},
	{"POST", "/api/entities/vc/entity"},
	{"POST", "/api/entities/vc/version"},
	{"POST", "/api/notification/entitiesLimitIncreaseRequest/{id}"},
	{"POST", "/api/notification/target/recipients"},
	{"POST", "/api/ruleChain/device/default"},
	{"POST", "/api/ruleChain/metadata"},
	{"POST", "/api/ruleChain/{id}/autoAssignToEdge"},
	{"POST", "/api/ruleChain/{id}/edgeTemplateRoot"},
	{"POST", "/api/ruleChain/{id}/root"},
	{"PUT", "/api/apiKey/{id}/description"},
	{"PUT", "/api/apiKey/{id}/enabled/{id}"},
	{"PUT", "/api/domain/{id}/oauth2Clients"},
	{"PUT", "/api/mobile/bundle/{id}/oauth2Clients"},
	{"PUT", "/api/notification/{id}/read"},
}
